#!/usr/bin/python3
print ("Content-type:text/html\r\n\r\n")
print("<html>")
print("<head>")
print("<title>Script CGI Python</title>")
print("</head>")
print("<body>")
print("<h1>Hello, world! This is a Python CGI .</h1>")
print("</body>")
print("</html>")